apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../definitions/gtn-demo-base
patches:
- path: patch.yaml
  target:
    kind: Tenant
- patch: |-
    - op: replace
      path: /metadata/name
      value: gtn-demo-2
  target:
    kind: Tenant
