apiVersion: gentianos.io/v1alpha1
kind: Tenant
metadata:
  name: gtn-demo-2
spec:
  domain: gtn-demo-2.desk.gentian.org
  adminEmail: admin-gtn-demo-2@gentian.org
  displayName: Gentian Demo 2
  isolation:
    databasePrefix: gtn2_
    keycloakRealm: gtn-demo-2
    ldapOU: ou=gtn-demo-2
    s3Prefix: gtn-demo-2-
  deletionPolicy: Delete
  apps:
  - profile: ox-appsuite
  - profile: element
    isolationMode: dedicated
