apiVersion: gentianos.io/v1alpha1
kind: Tenant
metadata:
  name: gtn-demo-2
spec:
  adminEmail: admin-gtn-demo-2@gentian.org
  apps:
  - profile: element
  deletionPolicy: Retain
  displayName: Gentian Demo 2
  domain: desk.gentian.org
  isolation:
    databasePrefix: gtn2_
    keycloakRealm: gtn-demo-2
    ldapOU: ou=gtn-demo-2
    mode: namespace
    s3Prefix: gtn-demo-2-
  mail:
    domain: gentian.org
    mode: selfhosted
    quotaPerUser: 5Gi
    rateLimit: 100/h
  quotas:
    cpu: 32
    maxApps: 20
    memory: 32Gi
    storage: 100Gi
