apiVersion: gentianos.io/v1alpha1
kind: Tenant
metadata:
  name: gtn-demo
spec:
  adminEmail: admin-gtn-demo@gentian.org
  displayName: Gentian Demo
  isolation:
    databasePrefix: gtn_
    keycloakRealm: gtn-demo
    ldapOU: ou=gtn-demo
    s3Prefix: gtn-demo-
  apps:
  - profile: ox-appsuite
  - profile: element
    isolationMode: shared
