apiVersion: gentianos.io/v1alpha1
kind: Tenant
metadata:
  name: gtn-demo
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  adminEmail: admin-gtn-demo@gentian.org
  apps:
  - profile: element
    isolationMode: shared
    config:
      extraValues:
        configuration:
          homeserver:
            user_directory:
              search_all_users: false
  deletionPolicy: Retain
  displayName: Gentian Demo
  domain: desk.gentian.org
  isolation:
    databasePrefix: gtn_
    keycloakRealm: gtn-demo
    ldapOU: ou=gtn-demo
    mode: namespace
    s3Prefix: gtn-demo-
  mail:
    domain: gentian.org
    mode: selfhosted
    quotaPerUser: 5Gi
    rateLimit: 100/h
  quotas:
    cpu: 32
    maxApps: 20
    memory: 32Gi
    storage: 100Gi
