apiVersion: gentianos.io/v1alpha1
kind: Tenant
metadata:
  name: gtn-demo
spec:
  adminEmail: admin@gentian.org
  apps:
  - profile: ox-appsuite
  - profile: openproject
  - profile: collabora
  deletionPolicy: Retain
  displayName: Gentian Demo
  domain: desk.gentian.org
  isolation:
    databasePrefix: gtn_
    keycloakRealm: gtn-demo
    ldapOU: ou=gtn-demo,${UDM_LDAP_BASE}
    mode: namespace
    s3Prefix: gtn-demo-
  mail:
    domain: gentian.org
    mode: selfhosted
    quotaPerUser: 5Gi
    rateLimit: 100/h
  quotas:
    cpu: '32'
    maxApps: 20
    memory: 32Gi
    storage: 100Gi
